id: P52E19153
initial_creation_type: input
source_metadata:
  title: Karse Kongtrul Khyentse Özer
  language: en
  description: 'Texts by and about Karse Kongtrul Khyentse Özer (kar sras kong sprul
    mkhyen brtse''i ''od zer, 1904–c.1953) who was a reincarnation of Jamgön Kongtrul
    and son of the Fifteenth Karmapa:'
  volume:
    233c7bd02bc34f55807c0e9682a598d7:
      title: Prayer to Karma Palden Khyentse
      parent: Prayers
created_at: '2022-03-01T00:12:40.457573'
last_modified_at: '2022-03-01T00:12:40.457579'
